#!/bin/sh

case "$1" in
    lock)
        $HOME/.config/i3/lock.sh
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        $HOME/.config/i3/lock.sh && systemctl suspend
        ;;
    hibernate)
        $HOME/.config/i3/lock.sh && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
