#!/bin/sh

case "$1" in
    lock)
        i3lock -c 111111
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        slock systemctl suspend
        ;;
    hibernate)
        slock systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
